# Generated by Django 3.2.7 on 2021-10-04 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(choices=[('author', 'Author'), ('contributor', 'Contributor')], max_length=20)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=1000)),
                ('type', models.TextField(choices=[('back', 'Back-end'), ('front', 'Front-end'), ('ios', 'iOS'), ('android', 'Android')])),
                ('contributors', models.ManyToManyField(to='projects.Contributor')),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('tag', models.CharField(choices=[('bug', 'Bug'), ('amelioration', 'Amelioration'), ('tache', 'Tache')], max_length=12)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('mid', 'Middle'), ('high', 'High')], max_length=12)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('inprogress', 'In Progress'), ('done', 'Done')], max_length=20)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('assigne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigne', to='projects.contributor')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='projects.contributor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.contributor')),
                ('issues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.issues')),
            ],
        ),
    ]
