# Generated by Django 3.2.7 on 2021-10-05 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20211005_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='permissions',
            new_name='permission',
        ),
        migrations.RenameField(
            model_name='contributor',
            old_name='roles',
            new_name='role',
        ),
    ]
