# Generated by Django 3.2.7 on 2021-10-05 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20211005_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='project',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='issues',
            name='assigne',
        ),
        migrations.RemoveField(
            model_name='issues',
            name='author',
        ),
        migrations.RemoveField(
            model_name='issues',
            name='project',
        ),
        migrations.DeleteModel(
            name='Commentaire',
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
        migrations.DeleteModel(
            name='Issues',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
